{{- if and $.Values.basicAuth.create $.Values.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "seleniumGrid.basicAuth.secrets.fullname" $ }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.basicAuth.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
type: Opaque
data:
{{- if eq .Values.basicAuth.enabled true }}
  SE_ROUTER_USERNAME: {{ .Values.basicAuth.username | b64enc }}
  SE_ROUTER_PASSWORD: {{ .Values.basicAuth.password | b64enc }}
{{- end }}
{{- end }}
