{{- range $i, $newNode := .Values.crossBrowsers.edgeNode }}
{{- $nodeConfig := merge $newNode $.Values.edgeNode -}}
{{- if and $nodeConfig.enabled (eq (include "seleniumGrid.useKEDA" $) "true") (eq $.Values.autoscaling.scalingType "job") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ template "seleniumGrid.edgeNode.fullname" (list $nodeConfig $) }}
  namespace: {{ $.Release.Namespace }}
  {{- if $.Values.autoscaling.annotations }}
  annotations:
    {{- with $.Values.autoscaling.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    app: {{ template "seleniumGrid.edgeNode.fullname" (list $nodeConfig $) }}
    app.kubernetes.io/name: {{ template "seleniumGrid.edgeNode.fullname" (list $nodeConfig $) }}
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
    {{- include "seleniumGrid.autoscalingLabels" $ | nindent 4 }}
    {{- with $nodeConfig.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- $podScope := deepCopy $ -}}
  {{- $_ := set $podScope "name" (include "seleniumGrid.edgeNode.fullname" (list $nodeConfig $)) -}}
  {{- $_ =  set $podScope "node" $nodeConfig -}}
  {{- $_ =  set $podScope "recorder" (mergeOverwrite $.Values.videoRecorder $nodeConfig.videoRecorder) -}}
  {{- $_ =  set $podScope "uploader" (get $.Values.videoRecorder ($podScope.recorder.uploader.name | toString)) -}}
  {{- $_ =  set $podScope "podTemplate" (include "seleniumGrid.podTemplate" $podScope | fromYaml) }}
  {{- include "seleniumGrid.autoscalingTemplate" $podScope | nindent 2 }}
---
{{- end }}
{{- end }}
