{{- range $i, $newNode := .Values.crossBrowsers.edgeNode }}
{{- $nodeConfig := merge $newNode $.Values.edgeNode -}}
{{- if and $nodeConfig.enabled (eq (include "seleniumGrid.useKEDA" $) "true") (eq $.Values.autoscaling.scalingType "deployment") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ template "seleniumGrid.edgeNode.fullname" (list $nodeConfig $) }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- with $.Values.autoscaling.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    deploymentName: {{ template "seleniumGrid.edgeNode.fullname" (list $nodeConfig $) }}
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
    {{- include "seleniumGrid.autoscalingLabels" $ | nindent 4 }}
    {{- with $nodeConfig.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- $podScope := deepCopy $ -}}
  {{- $_ := set $podScope "name" (include "seleniumGrid.edgeNode.fullname" (list $nodeConfig $)) -}}
  {{- $_ =  set $podScope "node" $nodeConfig -}}
  {{- include "seleniumGrid.autoscalingTemplate" $podScope | nindent 2 }}
---
{{- end }}
{{- end }}
