{{- if eq (include "seleniumGrid.monitoring.enabled" $) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "seleniumGrid.monitoring.exporter.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.monitoring.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
type: Opaque
data:
  {{- $key := include "seleniumGrid.monitoring.scrape.key" $ -}}
  {{- $value := tpl $.Values.monitoring.additionalScrapeConfigs.value $ -}}
  {{- if empty $value -}}
  {{- range $path, $_ := .Files.Glob "configs/scrape/*.yaml" }}
  {{ $key }}: {{ tpl ($.Files.Get $path) $ | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end -}}
{{- end }}
