apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "seleniumGrid.server.configmap.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.serverConfigMap.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
data:
  SE_SERVER_PROTOCOL: {{ include "seleniumGrid.server.protocol" . | quote }}
{{- if eq (include "seleniumGrid.server.secureConnection" $) "true" }}
  SE_ENABLE_TLS: "true"
  SE_HTTPS_CERTIFICATE: {{ printf "%s/%s" .Values.tls.certVolumeMountPath .Values.tls.certificateFile | quote }}
  SE_HTTPS_PRIVATE_KEY: {{ printf "%s/%s" .Values.tls.certVolumeMountPath .Values.tls.privateKeyFile | quote }}
  SE_JAVA_SSL_TRUST_STORE: {{ printf "%s/%s" .Values.tls.certVolumeMountPath .Values.tls.trustStoreFile | quote }}
  SE_JAVA_SSL_TRUST_STORE_PASSWORD: {{ printf "%s/%s" .Values.tls.certVolumeMountPath .Values.tls.trustStorePasswordFile | quote }}
  SE_JAVA_DISABLE_HOSTNAME_VERIFICATION: {{ .Values.tls.disableHostnameVerification | quote }}
{{- end }}
{{- range $key, $value := $.Values.serverConfigMap.data }}
  {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
