apiVersion: v2
type: application
name: athena-demo
version: 0.0.1
description: Athena demo helm chart
home: https://github.com/catools2/athena
appVersion: 0.1.1
dependencies:
  - name: pgadmin4
    version: 1.36.0
    repository: https://helm.runix.net
    condition: pgadmin4.enabled
  - name: postgresql
    version: 16.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: opentelemetry-collector
    version: 0.117.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
  - name: jaeger
    version: 3.4.0
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled
  - name: prometheus
    version: 27.4.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 8.10.1
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: opensearch
    version: 2.31.0
    repository: https://opensearch-project.github.io/helm-charts
    condition: opensearch.enabled
