server.port=8080
spring.application.name=init
athena.schema.name=athena

spring.config.import=\
  classpath:defaults/spring_fixes.properties,\
  classpath:defaults/datasource.properties,\
  classpath:defaults/flyway.properties,\
  classpath:defaults/hikari.properties,\
  classpath:defaults/jpa.properties,\
  classpath:defaults/logging.properties,\
  classpath:defaults/otel.properties
