{
 "title": "Batch :: Batch Jobs Statistics",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "influx_datasource", "label": "Metrics (InfluxDB)", "query": "influxdb" },
   {
    "name": "svc_name",
    "label": "name",
    "query": "from(bucket: \"batch_job\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"svc_name\"])\n  |> group(columns: [])\n  |> distinct(column: \"svc_name\")\n  |> sort(columns: [\"svc_name\"])\n"
   },
   {
    "name": "svc_env",
    "label": "env",
    "query": "from(bucket: \"batch_job\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"svc_name\"] == \"${svc_name}\")\n  |> keep(columns: [\"svc_env\"])\n  |> group(columns: [])\n  |> distinct(column: \"svc_env\")\n  |> sort(columns: [\"svc_env\"])"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "from(bucket: \"batch_job\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.svc_env == \"${svc_env}\" and r.svc_name == \"${svc_name}\")\n  |> keep(columns: [\"svc_domain\", \"svc_name\"])\n  |> map(fn: (r) => ({\n      r with\n      cluster:\n        if r.svc_name == \"pr\" then \"cluster-prod-a\"\n        else if r.svc_domain == \"prod\" then \"cluster-prod-b\"\n        else \"cluster-nonprod\"\n  }))\n  |> group(columns: [])\n  |> distinct(column: \"cluster\")\n  |> sort(columns: [\"cluster\"])\n"
   },
   {
    "name": "job_name",
    "label": "Job Name",
    "query": "from(bucket: \"batch_job\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"svc_env\"] == \"${svc_env}\" and r[\"svc_name\"] == \"${svc_name}\")\n  |> keep(columns: [\"_measurement\"])\n  |> group(columns: [])\n  |> distinct(column: \"_measurement\")\n  |> sort(columns: [\"_measurement\"])"
   },
   { "name": "sa_datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "k8s_datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "application", "label": "application", "query": "batch" }
  ]
 },
 "panels": [
  { "title": "Batch Table Growth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"roct_stat\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => r[\"svc_name\"] == \"${svc_name}\")\n  |> filter(fn: (r) => r[\"svc_env\"] == \"${svc_env}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Vendor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"roct_stat\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vendor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => r[\"svc_name\"] == \"${svc_name}\")\n  |> filter(fn: (r) => r[\"svc_env\"] == \"${svc_env}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Client-Vendor Relationship",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"roct_stat\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client_vendor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => r[\"svc_name\"] == \"${svc_name}\")\n  |> filter(fn: (r) => r[\"svc_env\"] == \"${svc_env}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Address",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"roct_stat\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"address\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => r[\"svc_name\"] == \"${svc_name}\")\n  |> filter(fn: (r) => r[\"svc_env\"] == \"${svc_env}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Contact",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"roct_stat\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"contact\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => r[\"svc_name\"] == \"${svc_name}\")\n  |> filter(fn: (r) => r[\"svc_env\"] == \"${svc_env}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Batch Execution Pattern", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total Execution Trend",
   "type": "timeseries",
   "description": "Total Batch Job Executions",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"batch_job\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"job_start_time\" and contains(value: r._measurement, set: ${job_name:json}) and r.svc_name == \"$svc_name\" and r.svc_env == \"$svc_env\") \n  |> map(fn: (r) => ({\n      _time: time(v: r._value),\n      _value: 1\n  }))\n  |> aggregateWindow(every: ${interval}, fn: sum)\n  |> yield(name: \"job_count_over_time\")"
    }
   ]
  },
  {
   "title": "Total Execution Trend By Job",
   "type": "timeseries",
   "description": "Batch Job Execution Trend",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"batch_job\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"job_start_time\" and contains(value: r._measurement, set: ${job_name:json}) and r.svc_name == \"$svc_name\" and r.svc_env == \"$svc_env\") \n  |> map(fn: (r) => ({\n      _time: time(v: r._value),\n      _value: 1,\n      job: r._measurement\n  }))\n  |> group(columns: [\"job\"])\n  |> aggregateWindow(every: ${interval}, fn: sum)\n  |> yield(name: \"job_count_over_time\")\n"
    }
   ]
  },
  {
   "title": "Total Write Count Trend",
   "type": "timeseries",
   "description": "Total Write Operation For Batch Job Execution",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"batch_job\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n       r._field == \"write_count\" and \n       r.svc_name == \"$svc_name\" and \n       r.svc_env == \"$svc_env\" and \n       contains(value: r._measurement, set: ${job_name:json})\n  )\n  |> aggregateWindow(every: ${interval}, fn: sum)\n  |> map(fn: (r) => ({\n      r with\n      job: r._measurement\n  }))\n  |> keep(columns: [\"job\", \"_value\", \"_time\"])\n  |> group(columns: [\"job\"])"
    }
   ]
  },
  {
   "title": "Max Write Count Trend",
   "type": "timeseries",
   "description": "The Maximum Number Of Write Operations for Batch Job Execution",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"batch_job\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (r._field == \"job_start_time\" or r._field == \"write_count\") and r.svc_name == \"$svc_name\" and r.svc_env == \"$svc_env\") \n  |> pivot(\n    rowKey: [\"_time\", \"_measurement\"], \n    columnKey: [\"_field\"], \n    valueColumn: \"_value\"\n  )\n  |> map(fn: (r) => ({\n      _time: time(v: r.job_start_time),\n      _value: float(v: r.write_count),\n      job: r._measurement\n  }))\n  |> filter(fn: (r) => contains(value: r.job, set: ${job_name:json})) \n  |> group(columns: [\"job\"])\n  |> aggregateWindow(every: ${interval}, fn: max)\n  |> yield(name: \"commit_sum_over_job_start_time\")\n"
    }
   ]
  },
  {
   "title": "Total Job Duration (Seconds)",
   "type": "timeseries",
   "description": "Total Commit Operation For Batch Job Execution",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"batch_job\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n       r._field == \"job_duration\" and \n       r.svc_name == \"$svc_name\" and \n       r.svc_env == \"$svc_env\" and \n       contains(value: r._measurement, set: ${job_name:json})\n  )\n  |> aggregateWindow(every: ${interval}, fn: sum)\n  |> map(fn: (r) => ({\n      r with\n      job: r._measurement\n  }))\n  |> keep(columns: [\"job\", \"_value\", \"_time\"])\n  |> group(columns: [\"job\"])"
    }
   ]
  },
  {
   "title": "Max Job Duration (Seconds)",
   "type": "timeseries",
   "description": "The Maximum Number Of Commit Operations for Batch Job Execution",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"batch_job\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (r._field == \"job_start_time\" or r._field == \"job_duration\") and r.svc_name == \"$svc_name\" and r.svc_env == \"$svc_env\")\n  |> pivot(\n    rowKey: [\"_time\", \"_measurement\"], \n    columnKey: [\"_field\"], \n    valueColumn: \"_value\"\n  )\n  |> map(fn: (r) => ({\n      _time: time(v: r.job_start_time),\n      _value: int(v: r.job_duration),\n      job: r._measurement\n  }))\n  |> filter(fn: (r) => contains(value: r.job, set: ${job_name:json})) \n  |> group(columns: [\"job\"])\n  |> aggregateWindow(every: ${interval}, fn: max)\n  |> yield(name: \"max_job_duration\")\n"
    }
   ]
  },
  {
   "title": "Failed Batch Job Trend",
   "type": "timeseries",
   "description": "Batch Job Execution Trend",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: \"batch_job\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"job_status\"] == \"FAILED\" and r._field == \"job_start_time\" and contains(value: r._measurement, set: ${job_name:json}) and r.svc_name == \"$svc_name\" and r.svc_env == \"$svc_env\") \n  |> map(fn: (r) => ({\n      _time: time(v: r._value),\n      _value: 1,\n      job: r._measurement\n  }))\n  |> group(columns: [\"job\"])\n  |> aggregateWindow(every: ${interval}, fn: sum)\n  |> yield(name: \"job_count_over_time\")\n"
    }
   ]
  },
  {
   "title": "Batch Pod - Resource Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Total Batch Process CPU Usage",
   "type": "timeseries",
   "description": "See more details <a href=\"https://grafana.example.com/goto/XnoQr8XNR?orgId=1\">here</a>",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\"})",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Total Batch Live Threads",
   "type": "timeseries",
   "description": "See more details <a href=\"https://grafana.example.com/goto/XnoQr8XNR?orgId=1\">here</a>",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\"})",
     "legendFormat": "Live"
    },
    {
     "expr": "sum(jvm_threads_states_threads{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\", state=\"runnable\"})",
     "legendFormat": "Runnable"
    },
    {
     "expr": "sum(jvm_threads_states_threads{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\", state=\"waiting\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(jvm_threads_states_threads{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\", state=\"blocked\"})",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Total Batch Active Connections",
   "type": "timeseries",
   "description": "See more details <a href=\"https://grafana.example.com/goto/XnoQr8XNR?orgId=1\">here</a>",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\"})",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Total Batch Used Heap",
   "type": "timeseries",
   "description": "See more details <a href=\"https://grafana.example.com/goto/XnoQr8XNR?orgId=1\">here</a>",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\"}) by (area) / sum(jvm_memory_max_bytes{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\"}) by (area)) * 100",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Batch Process CPU Usage",
   "type": "timeseries",
   "description": "See more details <a href=\"https://grafana.example.com/goto/XnoQr8XNR?orgId=1\">here</a>",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "process_cpu_usage{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Batch Live Threads",
   "type": "timeseries",
   "description": "See more details <a href=\"https://grafana.example.com/goto/XnoQr8XNR?orgId=1\">here</a>",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\"}",
     "legendFormat": "{{exported_instance}}-Live"
    },
    {
     "expr": "jvm_threads_states_threads{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\", state=\"runnable\"}",
     "legendFormat": "{{exported_instance}}-Runnable"
    },
    {
     "expr": "jvm_threads_states_threads{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\", state=\"waiting\"}",
     "legendFormat": "{{exported_instance}}-Waiting"
    },
    {
     "expr": "jvm_threads_states_threads{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\", state=\"blocked\"}",
     "legendFormat": "{{exported_instance}}-Blocked"
    }
   ]
  },
  {
   "title": "Batch Active Connections",
   "type": "timeseries",
   "description": "See more details <a href=\"https://grafana.example.com/goto/XnoQr8XNR?orgId=1\">here</a>",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Batch Total Used Heap",
   "type": "timeseries",
   "description": "See more details <a href=\"https://grafana.example.com/goto/XnoQr8XNR?orgId=1\">here</a>",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 52 },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\"}) by (area, exported_instance) / sum(jvm_memory_max_bytes{bt_tier=~\"$svc_name\", svc_env=~\"$svc_env\", application=\"$application\"}) by (area, exported_instance)) * 100",
     "legendFormat": "{{area}}-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Batch Database - Resource Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }
  },
  {
   "title": "Connections per DB & User",
   "type": "timeseries",
   "description": "Find more details <a href=\"https://grafana.example.com/goto/ijgf98XHR?orgId=1\">here</a>",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum by (datname,state,usename) (pg_stat_activity_count{datname=\"batch\", usename=~\"batch.*\",state=~\"active|idle in transaction.*|idle\"}) > 0",
     "legendFormat": "{{usename}}-{{state}}"
    }
   ]
  },
  {
   "title": "Buffer hits IOs (15m Interval)",
   "type": "timeseries",
   "description": "Find more details <a href=\"https://grafana.example.com/goto/ijgf98XHR?orgId=1\">here</a>",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_blks_hit{datname=\"batch\",datid!=''}[15m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}