{
 "title": "QE :: Environment Healthcheck",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "athena_datasource", "label": "Athena database", "query": "grafana-postgresql-datasource" },
   {
    "name": "environment",
    "label": "environment",
    "query": "SELECT distinct environment\nFROM athena.vw_pipeline_product_monitoring_statistic\nWHERE $__timeFilter(start_date)"
   },
   {
    "name": "name",
    "label": "name",
    "query": "SELECT distinct class_name\nFROM athena.vw_pipeline_product_monitoring_statistic\nWHERE $__timeFilter(start_date)\n"
   },
   {
    "name": "lastExecution",
    "query": "SELECT \n  to_char(e.end_time AT TIME ZONE 'UTC', 'DD Mon YYYY HH24:MI:SS') AS last_execution\nFROM athena_pipeline.execution e\nWHERE e.pipeline_id = (\n    SELECT p.id\n    FROM athena_pipeline.pipeline p\n    JOIN athena_core.environment env ON p.environment_id = env.id\n    LEFT JOIN athena_core.app_version v ON p.version_id = v.id\n    LEFT JOIN athena_core.project proj ON v.project_id = proj.id\n    WHERE proj.code::text = 'DEMO'::text\n      AND p.start_date > (now() - '1 mon'::interval)\n      AND p.name::text ~~ 'Monitoring - QA Validation Tests'::text\n       AND env.name = '$environment'  \n      AND p.start_date IS NOT NULL\n    ORDER BY p.start_date DESC\n    LIMIT 1\n)\nORDER BY e.end_time DESC\nLIMIT 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Execution: $lastExecution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Execution Status",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "WITH latest_pipeline AS (\r\n  SELECT p.id\r\n  FROM athena_pipeline.pipeline p\r\n  JOIN athena_core.environment env ON p.environment_id = env.id\r\n  LEFT JOIN athena_core.app_version v ON p.version_id = v.id\r\n  LEFT JOIN athena_core.project proj ON v.project_id = proj.id\r\n  WHERE proj.code::text = 'DEMO'::text\r\n      AND p.start_date > (now() - '1 mon'::interval)\r\n      AND p.name::text ~~ 'Monitoring - QA Validation Tests'::text\r\n      AND p.start_date IS NOT null\r\n      AND env.name = '$environment'                -- <--- filter here\r\n  ORDER BY p.start_date DESC\r\n  LIMIT 1\r\n)\r\nSELECT\r\n    COUNT(*) AS count,\r\n    s.name AS status\r\nFROM (\r\n    SELECT DISTINCT ON (e.class_name)\r\n        e.class_name,\r\n        s.name\r\n    FROM athena_pipeline.execution e\r\n    JOIN athena_pipeline.status s ON e.status_id = s.id\r\n    WHERE e.pipeline_id = (SELECT id FROM latest_pipeline)\r\n    ORDER BY e.class_name, e.end_time DESC\r\n) sub\r\nJOIN athena_pipeline.status s ON sub.name = s.name\r\nGROUP BY s.name\r\nORDER BY s.name;\r\n"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "rawSql": "WITH latest_pipeline AS (\r\n  SELECT p.id\r\n  FROM athena_pipeline.pipeline p\r\n  JOIN athena_core.environment env ON p.environment_id = env.id\r\n  LEFT JOIN athena_core.app_version v ON p.version_id = v.id\r\n  LEFT JOIN athena_core.project proj ON v.project_id = proj.id\r\n  WHERE proj.code::text = 'DEMO'::text\r\n      AND p.start_date > (now() - '1 mon'::interval)\r\n      AND p.name::text ~~ 'Monitoring - QA Validation Tests'::text\r\n       AND env.name = '$environment'  \r\n      AND p.start_date IS NOT NULL\r\n  ORDER BY p.start_date DESC\r\n  LIMIT 1\r\n)\r\nSELECT DISTINCT ON (e.class_name)\r\n    e.class_name,\r\n    s.name AS STATUS,\r\n    EXTRACT(EPOCH FROM (e.end_time - e.start_time)) AS duration\r\nFROM athena_pipeline.execution e\r\nJOIN athena_pipeline.status s ON e.status_id = s.id\r\nWHERE e.pipeline_id = (SELECT id FROM latest_pipeline)\r\nORDER BY e.class_name, e.end_time DESC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Execution status based on Select Date Range",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\nSELECT\r\n  ROUND(\r\n    100.0 * COALESCE(SUM(total_sucess), 0)\r\n    / NULLIF(COALESCE(SUM(total_execution), 0), 0),\r\n    2\r\n  ) AS PASS,\r\n  ROUND(\r\n    100.0 * COALESCE(SUM(total_failure + total_skip), 0)\r\n    / NULLIF(COALESCE(SUM(total_execution), 0), 0),\r\n    2\r\n  ) AS FAIL\r\nFROM athena.vw_pipeline_product_monitoring_statistic\r\nWHERE $__timeFilter(start_date)\r\n  AND environment = '$environment';\r\n"
    }
   ]
  },
  {
   "title": "Most Failed Tests",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT class_name, sucess_rate\r\nFROM athena. vw_pipeline_product_monitoring_statistic\r\nWHERE $__timeFilter(start_date) \r\n  AND environment = '$environment'\r\n  AND sucess_rate < 70\r\nORDER BY sucess_rate ASC;"
    }
   ]
  },
  {
   "title": "Batch",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT class_name, sucess_rate\r\nFROM athena. vw_pipeline_product_monitoring_statistic\r\nWHERE $__timeFilter(start_date) \r\n  AND class_name LIKE '%Batch%'\r\n  AND environment = '$environment'\r\nORDER BY sucess_rate ASC;"
    }
   ]
  },
  {
   "title": "Demo",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT class_name, sucess_rate\r\nFROM athena.vw_pipeline_product_monitoring_statistic\r\nWHERE $__timeFilter(start_date) \r\n  AND class_name IN ($name) \r\n  AND class_name NOT LIKE '%Batch%'\r\n  AND environment = '$environment'\r\n  AND sucess_rate >= 80\r\nORDER BY sucess_rate ASC;"
    }
   ]
  },
  {
   "title": "All Tests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$name",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 44 },
     "repeat": "name",
     "targets": [
      {
       "rawSql": "SELECT class_name, sucess_rate\nFROM athena.vw_pipeline_product_monitoring_statistic\nWHERE $__timeFilter(start_date) \n  AND class_name IN ($name) \n  AND environment = '$environment'\nORDER BY sucess_rate ASC\nLIMIT 1"
      }
     ]
    }
   ]
  },
  { "title": "Health Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "\n-- Build daily buckets for the dashboard range\nWITH buckets AS (\n  SELECT generate_series(\n    date_trunc('hour', $__timeFrom()::timestamp),\n    date_trunc('hour', $__timeTo()::timestamp),\n    interval '1 hour'\n  ) AS hour\n),\n-- Aggregate \"rate\" per class per day (you currently SUM, keeping that for shape)\nhourly AS (\n  SELECT\n    date_trunc('hour', start_date)          AS hour,\n    class_name                             AS metric,\n    SUM(sucess_rate)::double precision     AS executions   -- note: this is a rate being summed\n  FROM athena.vw_pipeline_product_monitoring_statistic\n  WHERE $__timeFilter(start_date) and environment = '$environment'\n  GROUP BY 1, 2\n),\nclasses AS (\n  SELECT DISTINCT metric FROM hourly\n),\ngrid AS (\n  SELECT b.hour, c.metric\n  FROM buckets b\n  CROSS JOIN classes c\n),\nfilled AS (\n  SELECT\n    g.hour,\n    g.metric,\n    COALESCE(d.executions, 0.0)::double precision AS executions\n  FROM grid g\n  LEFT JOIN hourly d\n    ON d.hour = g.hour AND d.metric = g.metric\n),\ncum AS (\n  SELECT\n    hour AS \"time\",\n    metric,\n    SUM(executions) OVER (\n      PARTITION BY metric\n      ORDER BY hour\n      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    )::double precision AS cum_value\n  FROM filled\n)\nSELECT\n  \"time\",\n  metric,\n  LEAST(cum_value, 100.0)::double precision AS value\nFROM cum\nORDER BY \"time\", metric\n"
    }
   ]
  }
 ]
}