{
 "title": "QE :: QA Dashboard",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "athena_datasource", "label": "Athena database", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Cumulative Test Inventory by Status (For Defined Range)",
   "type": "timeseries",
   "description": "Test creation trend by type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH daily AS (\n    SELECT\n        DATE_TRUNC('day', occurred) AS day,\n        SUM(need_review) AS need_review,\n        SUM(reviewed) AS reviewed,\n        SUM(review_in_progress) AS review_in_progress,\n        SUM(review_passed) AS review_passed,\n        SUM(rework_required) AS rework_required,\n        SUM(rework_required_automated) AS rework_required_automated,\n        SUM(manual) AS manual_delta,\n        SUM(automated) AS automated_delta,\n        SUM(automation_candidate) AS automation_candidate_delta,\n        SUM(automation_in_progress) AS automation_in_progress_delta,\n        SUM(dev_automated) AS dev_automated_delta,\n        SUM(dev_automation_candidate) AS dev_automation_candidate_delta,\n        SUM(dev_automation_in_progress) AS dev_automation_in_progress_delta,\n        SUM(playwright_automated) AS playwright_automated_delta,\n        SUM(playwright_automation_candidate) AS playwright_automation_candidate_delta,\n        SUM(playwright_automation_in_progress) AS playwright_automation_in_progress_delta\n    FROM athena.mv_inventory_trend\n    Where item_key ~~* 'demo-t%' and item_type = 'Test'\n    GROUP BY DATE_TRUNC('day', occurred)\n)\nSELECT\n    day AS \"time\",\n\n    SUM(need_review) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Need Review\",\n\n    SUM(reviewed) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Reviewed\",\n\n    SUM(review_in_progress) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Review In Progress\",\n\n    SUM(review_passed) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Review Passed\",\n\n    SUM(rework_required) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Rework Required\",\n\n    SUM(rework_required_automated) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Rework Required Automated\",\n\n    SUM(manual_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Manual\",\n\n    SUM(automated_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automated\",\n\n    SUM(automation_candidate_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automation Candidate\",\n\n\n    SUM(automation_in_progress_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automation In Progress\",\n\n    SUM(playwright_automated_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Playwright Automated\",\n\n    SUM(playwright_automation_candidate_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Playwright Automation Candidate\",\n\n\n    SUM(playwright_automation_in_progress_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Playwright Automation In Progress\",\n\n    SUM(dev_automated_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Dev Automated\",\n\n    SUM(dev_automation_candidate_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Dev Automation Candidate\",\n\n\n    SUM(dev_automation_in_progress_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Dev Automation In Progress\"\n\nFROM daily\nORDER BY day;\n"
    }
   ]
  },
  {
   "title": "Unique Tests In Regression Cycle",
   "type": "barchart",
   "description": "Total number of unique tests which has been executed for each regression ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT version AS version,\n                  sum(automated) AS \"Automated\",\n                  sum(sme) AS \"SME\",\n                  sum(manual) AS \"Manual\",\n                  sum(gdb) AS \"GoldenDB\",\n                  sum(playwright) as \"Playwright\"\nFROM athena.mv_regression_automation_to_manual_ratio\nWhere project_code = 'DEMO' and automated > 100\nGROUP BY version\nORDER BY \"Automated\""
    }
   ]
  },
  {
   "title": "Cumulative Test Inventory by Status (For Defined Range)",
   "type": "timeseries",
   "description": "Test creation trend by type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH daily AS (\n    SELECT\n        DATE_TRUNC('day', occurred) AS day,\n        SUM(need_review) AS need_review_delta,\n        SUM(reviewed) AS reviewed_delta,\n        SUM(review_in_progress) AS review_in_progress_delta,\n        SUM(review_passed) AS review_passed_delta,\n        SUM(rework_required) AS rework_required_delta,\n        SUM(rework_required_automated) AS rework_required_automated_delta,\n        SUM(manual) AS manual_delta,\n        SUM(automated) AS automated_delta,\n        SUM(automation_candidate) AS automation_candidate_delta,\n        SUM(automation_in_progress) AS automation_in_progress_delta,\n        SUM(playwright_automated) AS playwright_automated_delta,\n        SUM(playwright_automation_candidate) AS playwright_automation_candidate_delta,\n        SUM(playwright_automation_in_progress) AS playwright_automation_in_progress_delta,\n        SUM(dev_automated) AS dev_automated_delta,\n        SUM(dev_automation_candidate) AS dev_automation_candidate_delta\n    FROM athena.mv_inventory_trend\n    Where item_key ~~* 'demo-t%' and item_type = 'Test' and occurred between $__timeFrom() and $__timeTo() \n    GROUP BY DATE_TRUNC('day', occurred)\n)\nSELECT\n    day AS \"time\",\n\n    SUM(need_review_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Need Review\",\n\n    SUM(reviewed_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Reviewed\",\n\n    SUM(review_in_progress_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Review In Progress\",\n\n    SUM(review_passed_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Review Passed\",\n\n    SUM(rework_required_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Rework Required\",\n\n    SUM(rework_required_automated_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Rework Required Automated\",\n\n    SUM(manual_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Manual\",\n\n    SUM(automated_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automated\",\n\n    SUM(automation_candidate_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automation Candidate\",\n\n    SUM(playwright_automated_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Playwright Automated\",\n\n    SUM(automation_in_progress_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automation In Progress\",\n\n    SUM(playwright_automation_candidate_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Playwright Automation Candidate\",\n\n    SUM(playwright_automation_in_progress_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Playwright Automation In Progress\",\n\n    SUM(dev_automated_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Dev Automated\",\n\n    SUM(dev_automation_candidate_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Dev Automation Candidate\"\n\nFROM daily\nORDER BY day;\n"
    }
   ]
  },
  {
   "title": "Cumulative Automation Debt ",
   "type": "timeseries",
   "description": "Test creation trend by type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH daily AS (\n    SELECT\n        DATE_TRUNC('day', occurred) AS day,\n        SUM(manual + automation_candidate + automation_in_progress + playwright_automation_candidate + playwright_automation_in_progress + dev_automation_candidate + dev_automation_in_progress) AS quality_debt_delta\n    FROM athena.mv_inventory_trend\n    Where item_key ~~* 'demo-t%' and item_type = 'Test' and occurred between $__timeFrom() and $__timeTo()\n    GROUP BY DATE_TRUNC('day', occurred)\n)\nSELECT\n    day AS \"time\",\n\n    SUM(quality_debt_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Quality Debt\"\n\nFROM daily\nORDER BY day;\n"
    }
   ]
  },
  {
   "title": "Days From Created to Automated",
   "type": "barchart",
   "description": "Number of days between creation of test  to automate it",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('day', updated_on) AS \"time\",\n    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY EXTRACT(DAY FROM Age(updated_on, created_on))) FILTER (WHERE item_status = 'Automated') AS \"Automated\",\n    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY EXTRACT(DAY FROM Age(updated_on, created_on))) FILTER (WHERE item_status = 'Playwright Automated ') AS \"Playwright Automated\",\n    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY EXTRACT(DAY FROM Age(updated_on, created_on))) FILTER (WHERE item_status = 'Dev Automated') AS \"Dev Automated\"\nFROM athena.mv_items\nWhere item_key ~~* 'demo-t%' \n    and item_type = 'Test' \n    and item_status in ('Automated', 'Playwright Automated ', 'Dev Automated')\n    and updated_on between $__timeFrom() and $__timeTo() \nGROUP BY DATE_TRUNC('day', updated_on)\nORDER by DATE_TRUNC('day', updated_on)"
    }
   ]
  },
  {
   "title": "Total Defects",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "select\n  version,\n  sum(case when trim(environment_set ->> 0) = 'Production' then 1 else 0 end) as prod,\n  count(*) AS total\nFROM athena.mv_items i\nCROSS JOIN LATERAL jsonb_array_elements_text(affected_version_set) AS version\nWHERE i.project_code = 'DEMO' AND i.item_type = 'Bug'\nand version in ('4.3','4.4','4.5','4.6','4.7','4.8','4.9','4.10.0','4.11.0','4.12.0','4.13.0','4.14.0','4.15.0')\nGROUP by version\nORDER BY string_to_array(version, '.')::int[]"
    }
   ]
  },
  {
   "title": "Overall Test Inventory by Type",
   "type": "bargauge",
   "description": "Tests that have been created in a defined range by status",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n    item_status,\n    COUNT(DISTINCT item_id) AS total\nFROM athena.mv_items\nWHERE project_code = 'DEMO' and item_type = 'Test' and item_key ~~ 'DEMO-T%'\nGROUP BY item_status\nOrder by item_status\n"
    }
   ]
  },
  {
   "title": "Test Inventory Created In The Time Range",
   "type": "bargauge",
   "description": "Tests that have been created in a defined range by status",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n    item_status,\n    COUNT(DISTINCT item_id) AS total\nFROM athena.mv_items\nWHERE project_code = 'DEMO' and item_type = 'Test' and item_key ~~ 'DEMO-T%' and created_on BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY item_status\nOrder by item_status"
    }
   ]
  },
  {
   "title": "Overall Average Days To Last Test Update",
   "type": "bargauge",
   "description": "Average day to last update for the test that have been created in a defined range by status",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n    item_status,\n    avg(EXTRACT(DAY FROM (Age(updated_on, created_on)))) AS total\nFROM athena.mv_items\nWHERE project_code = 'DEMO' and item_type = 'Test'\nGroup by item_status\nOrder by item_status\n\n"
    }
   ]
  },
  {
   "title": "Average Days To Last Test Update For The Time Range",
   "type": "bargauge",
   "description": "Average day to last update for the test that have been created in a defined range by status",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n    item_status,\n    avg(EXTRACT(DAY FROM (Age(updated_on, created_on)))) AS total\nFROM athena.mv_items\nWHERE project_code = 'DEMO' and item_type = 'Test' and created_on BETWEEN $__timeFrom() AND $__timeTo()\nGroup by item_status\n"
    }
   ]
  }
 ]
}