{
 "title": "QE :: ___",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "athena_datasource", "label": "Athena database", "query": "grafana-postgresql-datasource" },
   {
    "name": "team",
    "label": "team",
    "query": "SELECT distinct jsonb_array_elements_text(teams_set)\nFROM athena.mv_test_cycle_statistics\nWHERE item_key ~~* 'demo-t%' and item_type = 'Test'"
   },
   {
    "name": "username",
    "label": "username",
    "query": "select distinct vcnu.username\nFROM athena.mv_items i\nLEFT JOIN athena.vw_core_normalized_users vcnu ON vcnu.id = i.updated_by\nWHERE project_code = 'DEMO' and item_type = 'Bug' \n  AND i.created_on between $__timeFrom() and $__timeTo()\n  AND EXISTS (\n        SELECT 1\n        FROM jsonb_array_elements_text(teams_set) AS team\n        WHERE team.value IN ($team)\n  )\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Created Defects by Type",
   "type": "bargauge",
   "description": "Defects that have been created in a defined range by status",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    item_status,\n    COUNT(DISTINCT item_id) AS total\nFROM athena.mv_items i\nLEFT JOIN athena.vw_core_normalized_users vcnu ON i.created_by = vcnu.id\nWHERE i.project_code = 'DEMO'\n  AND i.item_type = 'Bug'\n  AND i.created_on between $__timeFrom() and $__timeTo()\n  AND vcnu.username in ($username)\n  AND EXISTS (\n        SELECT 1\n        FROM jsonb_array_elements_text(teams_set) AS team\n        WHERE team.value IN ($team)\n  )\nGROUP BY item_status\nOrder by item_status"
    }
   ]
  },
  {
   "title": "Defects By created Day and Reporter",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', i.created_on) AS time,\n  vcnu.username AS metric,\n  COUNT(DISTINCT i.item_id) AS value\nFROM athena.mv_items i\nLEFT JOIN athena.vw_core_normalized_users vcnu ON i.created_by = vcnu.id\nWHERE i.project_code = 'DEMO'\n  AND i.item_type = 'Bug'\n  AND i.created_on between $__timeFrom() and $__timeTo()\n  AND vcnu.username in ($username)\n  AND EXISTS (\n        SELECT 1\n        FROM jsonb_array_elements_text(teams_set) AS team\n        WHERE team.value IN ($team)\n  )\nGROUP BY vcnu.username, DATE_TRUNC('day', i.created_on)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Defects By created Day and Team",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', i.created_on) AS time,\n  teams_set ->>0 AS metric,\n  COUNT(DISTINCT i.item_id) AS value\nFROM athena.mv_items i\nLEFT JOIN athena.vw_core_normalized_users vcnu ON i.created_by = vcnu.id\nWHERE i.project_code = 'DEMO'\n  AND i.item_type = 'Bug'\n  AND i.created_on between $__timeFrom() and $__timeTo()\n  AND vcnu.username in ($username)\n  AND EXISTS (\n        SELECT 1\n        FROM jsonb_array_elements_text(teams_set) AS team\n        WHERE team.value IN ($team)\n  )\nGROUP BY teams_set ->>0, DATE_TRUNC('day', i.created_on)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Created Defects by Reporter",
   "type": "bargauge",
   "description": "Defects that have been created in a defined range by status",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n    vcnu.username,\n    COUNT(DISTINCT item_id) AS total\nFROM athena.mv_items i\nleft join athena.vw_core_normalized_users vcnu on i.created_by = vcnu.id\nWHERE project_code = 'DEMO' and item_type = 'Bug'\nAND created_on between $__timeFrom() and $__timeTo()\nAND vcnu.username in ($username)\nAND EXISTS (\n    SELECT 1\n    FROM jsonb_array_elements_text(teams_set) AS team\n    WHERE team.value IN ($team)\n)\nGROUP BY vcnu.username\nOrder by 2 desc\n"
    }
   ]
  },
  {
   "title": "Created Defects by Reporter",
   "type": "bargauge",
   "description": "Defects that have been created in a defined range by status",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n    teams_set ->>0,\n    COUNT(DISTINCT item_id) AS total\nFROM athena.mv_items i\nleft join athena.vw_core_normalized_users vcnu on i.created_by = vcnu.id\nWHERE project_code = 'DEMO' and item_type = 'Bug'\nAND created_on between $__timeFrom() and $__timeTo()\nAND vcnu.username in ($username)\nAND EXISTS (\n    SELECT 1\n    FROM jsonb_array_elements_text(teams_set) AS team\n    WHERE team.value IN ($team)\n)\nGROUP BY teams_set ->>0\nOrder by 2 desc\n"
    }
   ]
  },
  {
   "title": "Reported Defects",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "select distinct i.item_key, i.item_status, i.name, i.created_on, i.updated_on, vcnu.username as created_by\nFROM athena.mv_items i\nLEFT JOIN athena.vw_core_normalized_users vcnu ON vcnu.id = i.created_by\nWHERE project_code = 'DEMO' and item_type = 'Bug'\nAND created_on between $__timeFrom() and $__timeTo()\nAND vcnu.username in ($username)\nAND EXISTS (\n    SELECT 1\n    FROM jsonb_array_elements_text(teams_set) AS team\n    WHERE team.value IN ($team)\n)\n"
    }
   ]
  },
  {
   "title": "Tests Created But Never Executed In Any Regression",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "type": "barchart",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 78 },
     "targets": [
      {
       "rawSql": "SELECT count(distinct i.item_id),\n       DATE_TRUNC('month', i.created_on) as month\nFROM athena.mv_items i\nLEFT JOIN athena.mv_test_cycle_statistics tcs\n       ON i.item_id = tcs.item_id\nWhere i.item_key ~~ 'DEMO-T%'\n       AND tcs.cycle_name LIKE '%Regression%'\n       AND i.created_on < NOW() - INTERVAL '4 months'\n       AND tcs.executed_on IS NULL\n       AND EXISTS (\n              SELECT 1\n              FROM jsonb_array_elements_text(tcs.teams_set) AS team\n              WHERE team.value IN ($team)\n       )\nGROUP BY DATE_TRUNC('month', i.created_on);\n"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 90 },
     "targets": [
      {
       "rawSql": "select distinct i.item_key, i.item_status, i.name, i.updated_on, vcnu.username as updated_by\nFROM athena.mv_items i\nLEFT JOIN athena.mv_test_cycle_statistics tcs ON i.item_id = tcs.item_id\nLEFT JOIN athena.vw_core_normalized_users vcnu ON vcnu.id = i.updated_by\nWhere i.item_key ~~ 'DEMO-T%'\n       AND tcs.cycle_name LIKE '%Regression%'\n       AND i.created_on < NOW() - INTERVAL '4 months'\n       AND tcs.executed_on IS NULL\n       AND EXISTS (\n              SELECT 1\n              FROM jsonb_array_elements_text(tcs.teams_set) AS team\n              WHERE team.value IN ($team)\n       )\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Tests Created But Not Executed In Regression In Past 2 Years",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }
  },
  {
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT count(distinct tcs.item_id),\n       DATE_TRUNC('month', tcs.created_on) as month\nFROM athena.mv_review_candidate_test tcs\nWhere tcs.item_key ~~ 'DEMO-T%'\nAND EXISTS (\n      SELECT 1\n      FROM jsonb_array_elements_text(tcs.teams_set) AS team\n      WHERE team.value IN ($team)\n)\nGROUP BY DATE_TRUNC('month', tcs.created_on);\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "rawSql": "select distinct rct.item_key, rct.item_name, rct.item_status, rct.created_on, rct.updated_on, rct.last_execution,rct.teams_set\nFROM athena.mv_review_candidate_test rct\nWhere rct.item_key ~~ 'DEMO-T%'\nAND EXISTS (\n      SELECT 1\n      FROM jsonb_array_elements_text(teams_set) AS team\n      WHERE team.value IN ($team)\n)\n"
    }
   ]
  }
 ]
}