x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    tag: "{{.Name}}"

x-common-variables: &common-variables
  ATHENA_DB_HOSTNAME: "athena-db"
  FLYWAY_ENABLED: "false"
  OTEL_TRACING_ENABLED: "false"
  LOG_LEVEL: "WARN"

x-common_service: &common_service
  pull_policy: if_not_present
  restart: unless-stopped
  logging: *logging
  networks:
    - athena-network

x-athena_core_dependent_service: &athena_core_dependent_service
  <<: *common_service
  depends_on:
    athena-db:
      condition: service_healthy
  deploy:
    resources:
      limits:
        memory: 512M
  healthcheck:
    test: curl -s http://localhost:$${APP_PORT}/actuator/health | grep UP || exit 1
    start_period: 30s
    interval: 15s
    timeout: 5s
    retries: 10

services:
  # Athena Demo Database
  athena-db:
    <<: *common_service
    image: akeshmiri/athena-pg-demo:0.2
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U "postgres" -d "athena"
      interval: 1s
      timeout: 5s
      retries: 60

  # Athena services
  athena-core:
    <<: *athena_core_dependent_service
    image: akeshmiri/athena-boot-core:latest
    ports:
      - 8081:8081
    environment:
      <<: *common-variables
      APP_PORT: 8081

networks:
  athena-network:
    driver: bridge