apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus-server.default.svc.cluster.local
    isDefault: true
  - name: Tempo
    type: tempo
    url: http://tempo-query-frontend.default.svc.cluster.local:3100
