{
 "title": "Batch :: Batch Steps Statistics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "influx_datasource", "label": "Metrics (InfluxDB)", "query": "influxdb" },
   {
    "name": "svc_name",
    "label": "name",
    "query": "from(bucket: \"batch_step\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"svc_name\"])\n  |> group(columns: [])\n  |> distinct(column: \"svc_name\")\n  |> sort(columns: [\"svc_name\"])\n"
   },
   {
    "name": "svc_env",
    "label": "env",
    "query": "from(bucket: \"batch_step\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"svc_name\"] == \"${svc_name}\")\n  |> keep(columns: [\"svc_env\"])\n  |> group(columns: [])\n  |> distinct(column: \"svc_env\")\n  |> sort(columns: [\"svc_env\"])"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "from(bucket: \"batch_step\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.svc_env == \"${svc_env}\" and r.svc_name == \"${svc_name}\")\n  |> keep(columns: [\"svc_domain\", \"svc_name\"])\n  |> map(fn: (r) => ({\n      r with\n      cluster:\n        if r.svc_name == \"pr\" then \"cluster-prod-a\"\n        else if r.svc_domain == \"prod\" then \"cluster-prod-b\"\n        else \"cluster-nonprod\"\n  }))\n  |> group(columns: [])\n  |> distinct(column: \"cluster\")\n  |> sort(columns: [\"cluster\"])\n"
   },
   {
    "name": "job_name",
    "label": "Job Name",
    "query": "from(bucket: \"batch_step\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"svc_env\"] == \"${svc_env}\" and r[\"svc_name\"] == \"${svc_name}\")\n  |> keep(columns: [\"_measurement\"])\n  |> group(columns: [])\n  |> distinct(column: \"_measurement\")\n  |> sort(columns: [\"_measurement\"])"
   },
   { "name": "sa_datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "k8s_datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "application", "label": "application", "query": "batch" }
  ]
 },
 "panels": [
  {
   "title": "Execution Per Step",
   "type": "timeseries",
   "description": "Total Number Of Batch Job Step Executions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"batch_step\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${job_name}\" and r.svc_name == \"$svc_name\" and r.svc_env == \"$svc_env\" and r._field == \"step_duration\")\n  |> group(columns: [\"step_name\"])\n  |> aggregateWindow(every: ${interval}, fn: count)\n"
    }
   ]
  },
  {
   "title": "Total Duration Per Step",
   "type": "timeseries",
   "description": "Total Duration In Seconds For Batch Job Step Executions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"batch_step\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${job_name}\" and r.svc_name == \"$svc_name\" and r.svc_env == \"$svc_env\" and r._field == \"step_duration\")\n  |> group(columns: [\"step_name\"])\n  |> aggregateWindow(every: ${interval}, fn: sum)\n"
    }
   ]
  },
  {
   "title": "Total Processed Records Per Step",
   "type": "timeseries",
   "description": "Total Number Of Records Processed by Each Step",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"batch_step\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${job_name}\" and r.svc_name == \"$svc_name\" and r.svc_env == \"$svc_env\" and r._field == \"max_count\")\n  |> group(columns: [\"step_name\"])\n  |> aggregateWindow(every: ${interval}, fn: sum)\n"
    }
   ]
  },
  {
   "title": "Total Failed Execution Step Execution",
   "type": "timeseries",
   "description": "Total Number Of Failed Batch Job Step Executions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"batch_step\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${job_name}\" and r.job_status == \"FAILED\" and r.svc_name == \"$svc_name\" and r.svc_env == \"$svc_env\" and r._field == \"step_duration\")\n  |> group(columns: [\"step_name\"])\n  |> aggregateWindow(every: ${interval}, fn: count)\n"
    }
   ]
  }
 ]
}