{
 "title": "Batch :: Batch Data Volume",
 "description": "Batch Tables Statistics (growth overtime,...)",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "influx_datasource", "label": "Metrics (InfluxDB)", "query": "influxdb" },
   {
    "name": "env",
    "label": "Environment",
    "query": "from(bucket: \"roct_stat\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> keep(columns: [\"svc_env\", \"svc_name\"])\n  |> map(fn: (r) => ({\n      r with\n      _value: r.svc_name + r.svc_env\n  }))\n  |> group(columns: [])\n  |> distinct(column: \"_value\")\n  |> sort(columns: [\"_value\"])\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "Batch Data Volume Dashboard\n\nThis dashboard provides a clear, real-time summary of the **number of records** stored in key database tables related to:\n\n- **Clients**\n- **Vendors**\n- **Client-Vendor Relationships**\n- **Addresses**\n\nIt tracks these record counts across three environments:\n- **PR2 (Production)** – Live operational data.\n- **PF2 (Release Performance)** – Used for testing new releases.\n- **PS3 (Patch Performance)** – Used for testing system patches and release regression testing.\n\n---\n\n### Purpose\n\nThe primary goal of this dashboard is to help teams to monitor and **predict future data growth** in the production environment over the next **12 to 18 months**. \nBy understanding how data volumes are trending, teams can:\n\n- **Estimate future production data size**\n- **Adjust performance test datasets** to reflect realistic future conditions\n- **Ensure system resilience and robustness** under high data load scenarios\n\nThis proactive approach helps maintain system stability and performance even during periods of significant change or growth."
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "## How to Use Filters in the Dashboard\n\nYour dashboard includes two key filters at the top: **Environment** and **Time Range**. \nThese filters help you customize the data view based on your needs.\n\n---\n\n### **Environment Filter**\n\nClick the dropdown labeled **Environment** at the top of the dashboard. Choose one or more of the options (PR2, PF2, or PS3) to view data specific to that environments. The dashboard will automatically refresh to show relevant record counts.\n\n---\n\n###  **Time Filter**\n\nTo see data for different time ranges, click the **Time Range** selector in the top-right corner of the dashboard. Choose a predefined range (e.g., Last 7 days) or click **Custom range** to select specific start and end dates. The dashboard will update to reflect data within that time window.\n\n---\n\n### **Tips for Effective Use**\n\nNarrow the **time range** to improve performance and focus on recent data.\n\n---\n\n### Query\n\n```sql\nselect count(*) from roct.client\nselect count(*) from roct.vendor\nselect count(*) from roct.client_vendor\nselect count(*) from roct.address\n```"
   }
  },
  {
   "title": "Client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"roct_stat\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => contains(value: r[\"svc_name\"] + r[\"svc_env\"], set: ${env:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with\n      series: r.svc_name + r.svc_env\n  }))\n  |> keep(columns: [\"series\", \"_value\", \"_time\"])\n  |> group(columns: [\"series\"])\n"
    }
   ]
  },
  {
   "title": "Vendor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"roct_stat\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vendor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => contains(value: r[\"svc_name\"] + r[\"svc_env\"], set: ${env:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with\n      series: r.svc_name + r.svc_env\n  }))\n  |> keep(columns: [\"series\", \"_value\", \"_time\"])\n  |> group(columns: [\"series\"])\n"
    }
   ]
  },
  {
   "title": "Client-Vendor Relationship",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"roct_stat\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"client_vendor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => contains(value: r[\"svc_name\"] + r[\"svc_env\"], set: ${env:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with\n      series: r.svc_name + r.svc_env\n  }))\n  |> keep(columns: [\"series\", \"_value\", \"_time\"])\n  |> group(columns: [\"series\"])\n"
    }
   ]
  },
  {
   "title": "Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"roct_stat\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"address\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => contains(value: r[\"svc_name\"] + r[\"svc_env\"], set: ${env:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with\n      series: r.svc_name + r.svc_env\n  }))\n  |> keep(columns: [\"series\", \"_value\", \"_time\"])\n  |> group(columns: [\"series\"])\n"
    }
   ]
  }
 ]
}