{
 "title": "QE :: QA Dashboard",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "athena_datasource", "label": "Athena database", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Unique Tests In Regression Cycle",
   "type": "barchart",
   "description": "Total number of unique tests which has been executed for each regression ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT version AS version,\n                  sum(automated) AS \"Automated\",\n                  sum(sme) AS \"SME\",\n                  sum(manual) AS \"Manual\",\n                  sum(gdb) AS \"GoldenDB\"\nFROM athena.mv_regression_automation_to_manual_ratio\nWhere project_code = 'DEMO' and automated > 100\nGROUP BY version\nORDER BY \"Automated\""
    }
   ]
  },
  {
   "title": "Cumulative Test Inventory by Status (For Defined Range)",
   "type": "timeseries",
   "description": "Test creation trend by type",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH daily AS (\n    SELECT\n        DATE_TRUNC('day', occurred) AS day,\n        SUM(need_review) AS need_review,\n        SUM(reviewed) AS reviewed,\n        SUM(review_in_progress) AS review_in_progress,\n        SUM(review_passed) AS review_passed,\n        SUM(rework_required) AS rework_required,\n        SUM(rework_required_automated) AS rework_required_automated,\n        SUM(manual) AS manual_delta,\n        SUM(automated) AS automated_delta,\n        SUM(automation_candidate) AS automation_candidate_delta,\n        SUM(automation_in_progress) AS automation_in_progress_delta,\n        SUM(dev_automated) AS dev_automated_delta,\n        SUM(dev_automation_candidate) AS dev_automation_candidate_delta,\n        SUM(dev_automation_in_progress) AS dev_automation_in_progress_delta\n    FROM athena.mv_inventory_trend\n    Where item_key ~~* 'demo-t%' and item_type = 'Test'\n    GROUP BY DATE_TRUNC('day', occurred)\n)\nSELECT\n    day AS \"time\",\n\n    SUM(need_review) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Need Review\",\n\n    SUM(reviewed) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Reviewed\",\n\n    SUM(review_in_progress) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Review In Progress\",\n\n    SUM(review_passed) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Review Passed\",\n\n    SUM(rework_required) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Rework Required\",\n\n    SUM(rework_required_automated) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Rework Required Automated\",\n\n    SUM(manual_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Manual\",\n\n    SUM(automated_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automated\",\n\n    SUM(automation_candidate_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automation Candidate\",\n\n\n    SUM(automation_in_progress_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automation In Progress\",\n\n    SUM(dev_automated_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Dev Automated\",\n\n    SUM(dev_automation_candidate_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Dev Automation Candidate\",\n\n\n    SUM(dev_automation_in_progress_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Dev Automation In Progress\"\n\nFROM daily\nORDER BY day;\n"
    }
   ]
  },
  {
   "title": "Cumulative Test Inventory by Status (For Defined Range)",
   "type": "timeseries",
   "description": "Test creation trend by type",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH daily AS (\n    SELECT\n        DATE_TRUNC('day', occurred) AS day,\n        SUM(need_review) AS need_review,\n        SUM(reviewed) AS reviewed,\n        SUM(review_in_progress) AS review_in_progress,\n        SUM(review_passed) AS review_passed,\n        SUM(rework_required) AS rework_required,\n        SUM(rework_required_automated) AS rework_required_automated,\n        SUM(manual) AS manual_delta,\n        SUM(automated) AS automated_delta,\n        SUM(automation_candidate) AS automation_candidate_delta,\n        SUM(automation_in_progress) AS automation_in_progress_delta,\n        SUM(dev_automated) AS dev_automated_delta,\n        SUM(dev_automation_candidate) AS dev_automation_candidate_delta,\n        SUM(dev_automation_in_progress) AS dev_automation_in_progress_delta\n    FROM athena.mv_inventory_trend\n    Where item_key ~~* 'demo-t%' and item_type = 'Test' and occurred between $__timeFrom() and $__timeTo() \n    GROUP BY DATE_TRUNC('day', occurred)\n)\nSELECT\n    day AS \"time\",\n\n    SUM(need_review) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Need Review\",\n\n    SUM(reviewed) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Reviewed\",\n\n    SUM(review_in_progress) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Review In Progress\",\n\n    SUM(review_passed) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Review Passed\",\n\n    SUM(rework_required) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Rework Required\",\n\n    SUM(rework_required_automated) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Rework Required Automated\",\n\n    SUM(manual_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Manual\",\n\n    SUM(automated_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automated\",\n\n    SUM(automation_candidate_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automation Candidate\",\n\n\n    SUM(automation_in_progress_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Automation In Progress\",\n\n    SUM(dev_automated_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Dev Automated\",\n\n    SUM(dev_automation_candidate_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Dev Automation Candidate\",\n\n\n    SUM(dev_automation_in_progress_delta) OVER (\n        ORDER BY day\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS \"Dev Automation In Progress\"\n\nFROM daily\nORDER BY day;\n"
    }
   ]
  },
  {
   "title": "Overall Test Inventory by Type",
   "type": "bargauge",
   "description": "Tests that have been created in a defined range by status",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n    item_status,\n    COUNT(DISTINCT item_id) AS total\nFROM athena.mv_items\nWHERE project_code = 'DEMO' and item_type = 'Test' and item_key ~~ 'DEMO-T%'\nGROUP BY item_status\nOrder by item_status\n"
    }
   ]
  },
  {
   "title": "Test Inventory by Type For The Time Range",
   "type": "bargauge",
   "description": "Tests that have been created in a defined range by status",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n    item_status,\n    COUNT(DISTINCT item_id) AS total\nFROM athena.mv_items\nWHERE project_code = 'DEMO' and item_type = 'Test' and item_key ~~ 'DEMO-T%' and created_on BETWEEN $__timeFrom() AND $__timeTo()\n\nGROUP BY item_status\nOrder by item_status"
    }
   ]
  },
  {
   "title": "Overall Average Days To Last Test Update",
   "type": "bargauge",
   "description": "Average day to last update for the test that have been created in a defined range by status",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n    item_status,\n    avg(EXTRACT(DAY FROM (Age(updated_on, created_on)))) AS total\nFROM athena.mv_items\nWHERE project_code = 'DEMO' and item_type = 'Test'\nGroup by item_status\nOrder by item_status\n\n"
    }
   ]
  },
  {
   "title": "Average Days To Last Test Update For The Time Range",
   "type": "bargauge",
   "description": "Average day to last update for the test that have been created in a defined range by status",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n    item_status,\n    avg(EXTRACT(DAY FROM (Age(updated_on, created_on)))) AS total\nFROM athena.mv_items\nWHERE project_code = 'DEMO' and item_type = 'Test' and created_on BETWEEN $__timeFrom() AND $__timeTo()\nGroup by item_status\n"
    }
   ]
  }
 ]
}