{
 "title": "QE :: Team Regression Statistics",
 "description": "Regression statistics per Team",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "athena_datasource", "label": "Athena database", "query": "grafana-postgresql-datasource" },
   {
    "name": "version",
    "label": "version",
    "query": "SELECT distinct version\nFROM athena.mv_test_cycle_statistics\nWHERE item_key ~~* 'demo-t%' and item_type = 'Test' and executed_on between $__timeFrom() and $__timeTo() and version like '4%'"
   },
   {
    "name": "team",
    "label": "team",
    "query": "SELECT distinct jsonb_array_elements_text(teams_set)\nFROM athena.mv_test_cycle_statistics\nWHERE item_key ~~* 'demo-t%' and item_type = 'Test' and executed_on between $__timeFrom() and $__timeTo() and version like '4%'"
   }
  ]
 },
 "panels": [
  {
   "title": "Contribution By Execution Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH categorized_cycles AS (\n    SELECT DISTINCT \n        tcs.item_id,\n        tcs.version,\n        tcs.teams_set,\n        CASE WHEN tcs.cycle_short_name LIKE '%Baseline%' THEN 1 ELSE 0 END AS baseline,\n        CASE WHEN tcs.cycle_short_name LIKE '%Automated%' THEN 1 ELSE 0 END AS automated,\n        CASE WHEN tcs.cycle_name NOT LIKE '%Automated%' THEN 1 ELSE 0 END AS manual\n    FROM athena.mv_test_cycle_statistics tcs\n    WHERE \n        tcs.cycle_name LIKE '%Regression%' \n        AND tcs.project_code = 'DEMO' \n        AND tcs.version = '$version'\n        AND tcs.teams_set ? '$team'\n        AND item_execution_rank = 1\n)\nSELECT\n    t.version,\n    SUM(t.automated) AS \"Automated\",\n    SUM(t.manual) AS \"Manual\",\n    SUM(t.baseline) AS \"Dev Automated\"\nFROM categorized_cycles t\nGROUP BY t.version\nORDER BY SUM(t.automated + t.manual + t.baseline)"
    }
   ]
  },
  {
   "title": "Manual Test Cycles Execution Status",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    cycle_short_name AS \"Test Cycle\",\n    SUM(pass + \"blocked\" + skipped + fail) / Sum(total)::float * 100 AS \"Total Executed\"\nFROM athena.mv_test_cycle_statistics\nWHERE cycle_name LIKE '%Regression%' \n    AND project_code = 'DEMO' \n    AND version = '$version'\n    AND teams_set ? '$team'\n    AND cycle_name NOT LIKE '%Automated%' \nGROUP BY cycle_short_name\n"
    }
   ]
  },
  {
   "title": "Automation Test Cycles Execution Status",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    cycle_short_name AS \"Test Cycle\",\n    SUM(pass + \"blocked\" + skipped + fail) / Sum(total)::float * 100 AS \"Total Executed\"\nFROM athena.mv_test_cycle_statistics\nWHERE cycle_name LIKE '%Regression%' \n    AND project_code = 'DEMO' \n    AND version = '$version'\n    AND teams_set ? '$team'\n    AND cycle_short_name LIKE '%Automated%' \nGROUP BY cycle_short_name\n"
    }
   ]
  },
  {
   "title": "Test Cycle Execution Dynamic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Manual Test Cycles Execution Rate (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n    SELECT \n        DATE_TRUNC('hour', executed_on) AS hour,\n        cycle_short_name AS \"Test Cycle\",\n        SUM(pass + \"blocked\" + skipped + fail) / MAX(cycle_size)::float * 100 AS \"Total Executed\"\n    FROM athena.mv_test_cycle_statistics\n    WHERE cycle_name LIKE '%Regression%' \n      AND project_code = 'DEMO' \n      AND version = '$version'\n      AND teams_set ? '$team'\n      AND cycle_name NOT LIKE '%Automated%' \n      AND executed_on IS NOT NULL\n    GROUP BY DATE_TRUNC('hour', executed_on), cycle_short_name\n)\nSELECT\n    COALESCE(hour, NOW()) AS \"time\",\n    \"Test Cycle\" AS metric,\n    SUM(\"Total Executed\") OVER (\n        PARTITION BY \"Test Cycle\"\n        ORDER BY COALESCE(hour, NOW())\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS value\nFROM daily\nORDER BY \"time\", \"Test Cycle\";\n"
      }
     ]
    },
    {
     "title": "Automated Test Cycles Execution Rate (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n    SELECT \n        DATE_TRUNC('hour', executed_on) AS hour,\n        cycle_short_name AS \"Test Cycle\",\n        SUM(pass + \"blocked\" + skipped + fail) / MAX(cycle_size)::float * 100 AS \"Total Executed\"\n    FROM athena.mv_test_cycle_statistics\n    WHERE cycle_name LIKE '%Regression%' \n      AND project_code = 'DEMO' \n      AND version = '$version'\n      AND teams_set ? '$team'\n      AND cycle_short_name LIKE '%Automated%' \n      AND executed_on IS NOT NULL\n    GROUP BY DATE_TRUNC('hour', executed_on), cycle_short_name\n)\nSELECT\n    COALESCE(hour, NOW()) AS \"time\",\n    \"Test Cycle\" AS metric,\n    SUM(\"Total Executed\") OVER (\n        PARTITION BY \"Test Cycle\"\n        ORDER BY COALESCE(hour, NOW())\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS value\nFROM daily\nORDER BY \"time\", \"Test Cycle\";\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall Test Cycles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Manual Test Cycles",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "rawSql": "SELECT cycle_short_name, count(*) AS total, sum(pass) AS pass, sum(fail) AS fail, sum(skipped) AS skipped, sum(blocked) AS blocked\nFROM athena.mv_test_cycle_statistics tcs\nWHERE \n    tcs.cycle_name LIKE '%Regression%' \n    AND tcs.project_code = 'DEMO' \n    AND version = '$version'\n    AND teams_set ? '$team'\n    AND cycle_name NOT LIKE '%Automated%' \n    AND item_execution_rank = 1\nGROUP BY cycle_short_name\nORDER BY cycle_short_name DESC\nLIMIT 100;\n"
      }
     ]
    },
    {
     "title": "Automation Test Cycles",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "rawSql": "SELECT cycle_short_name, count(*) AS total, sum(pass) AS pass, sum(fail) AS fail, sum(skipped) AS skipped, sum(blocked) AS blocked\nFROM athena.mv_test_cycle_statistics tcs\nWHERE \n    tcs.cycle_name LIKE '%Regression%' \n    AND tcs.project_code = 'DEMO' \n    AND version = '$version'\n    AND teams_set ? '$team'\n    AND cycle_short_name LIKE '%Automated%' \n    AND item_execution_rank = 1\nGROUP BY cycle_short_name\nORDER BY cycle_short_name DESC\nLIMIT 100;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Tests In Manual Test Cycles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "rawSql": "select item_key, item_status, name, cycle_code, cycle_short_name, executed_on, executor, execution_status from athena.mv_test_cycle_statistics\nWHERE cycle_name LIKE '%Regression%' \n  AND project_code = 'DEMO' \n  AND item_execution_rank = 1\n  AND version = '$version'\n  AND teams_set ? '$team'\n  AND cycle_name NOT LIKE '%Automated%' \n"
      }
     ]
    }
   ]
  },
  {
   "title": "Tests In Automation Test Cycles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "rawSql": "select item_key, item_status, name, cycle_code, cycle_short_name, executed_on, executor, execution_status from athena.mv_test_cycle_statistics\nWHERE cycle_name LIKE '%Regression%' \n  AND project_code = 'DEMO' \n  AND item_execution_rank = 1\n  AND version = '$version'\n  AND teams_set ? '$team'\n  AND cycle_short_name LIKE '%Automated%' \n"
      }
     ]
    }
   ]
  },
  {
   "title": "Tests In Dev Automation Test Cycles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "rawSql": "select item_key, item_status, name, cycle_code, cycle_short_name, executed_on, executor, execution_status from athena.mv_test_cycle_statistics\nWHERE cycle_name LIKE '%Regression%' \n  AND project_code = 'DEMO' \n  AND item_execution_rank = 1\n  AND version = '$version'\n  AND teams_set ? '$team'\n  AND cycle_short_name LIKE '%Baseline%' \n"
      }
     ]
    }
   ]
  },
  {
   "title": "Functional Area Coverage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "options": {
      "content": "<div style=\"font-family: Arial, sans-serif; color: var(--text-color, #333); background-color: var(--bg-color, #fafafa); padding: 12px; line-height: 1.6;\">\n    \n    <p><h4 style=\"color: var(--heading-color, #4db6ac);\">What this table shows:</h4>\n    This table lists test case counts for various <span style=\"color: var(--highlight-color, #81c784); font-weight:bold;\">functional areas</span> within the application, broken down by execution type (manual or automated) and associated execution status. Each row represents a specific functional area.</p>\n    \n    <p><h4 style=\"color: var(--heading-color, #4db6ac);\">Why it matters:</h4>\n    It provides visibility into how testing efforts are distributed across different parts of the application. This present the team functional area expertises and helps ensure that all critical areas receive adequate coverage during regression and hardening phases.</p>\n    \n    <p><h4 style=\"color: var(--heading-color, #4db6ac);\">How to interpret:</h4>\n    Since we follow a <span style=\"color: var(--warning-color, #ffb74d); font-weight:bold;\">risk-based testing approach</span>, different functional areas may have varying levels of risk impact. While generally, a high-risk area might have more automated tests for faster feedback, it is still possible that some complex areas may still require manual checks.</p>\n</div>"
     }
    },
    {
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT\n    area AS functional_area,\n    sum(CASE WHEN cycle_short_name LIKE '%Baseline%' THEN 1 ELSE 0 END) AS baseline,\n    sum(CASE WHEN cycle_short_name LIKE '%Automated%' THEN 1 ELSE 0 END) AS automated,\n    sum(CASE WHEN cycle_name NOT LIKE '%Automated%' THEN 1 ELSE 0 END) AS manual,\n    SUM(pass) AS \"Pass\",\n    SUM(fail) AS \"Fail\",\n    SUM(blocked) AS \"Blocked\",\n    SUM(in_progress) AS \"InProgress\",\n    SUM(skipped) AS \"Skipped\",\n    SUM(unexecuted) AS \"Unexecuted\",\n    SUM(in_progress + unexecuted) AS \"Total Unexecuted\",\n    COUNT(*) - SUM(in_progress + unexecuted) AS \"Total Executed\",\n    SUM(total) AS \"Total\"\nFROM athena.mv_test_cycle_statistics\nCROSS JOIN LATERAL jsonb_array_elements_text(functional_area_set) AS area\nWHERE cycle_name LIKE '%Regression%' \n  AND project_code = 'DEMO' \n  AND version = '$version'\n  AND teams_set ? '$team'\n  AND item_execution_rank = 1\nGROUP BY area\nORDER BY area\nLIMIT 10000"
      }
     ]
    }
   ]
  },
  {
   "title": "Coverage By Labels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "options": {
      "content": "<div style=\"font-family: Arial, sans-serif; color: var(--text-color, #333); background-color: var(--bg-color, #fafafa); padding: 12px; line-height: 1.6;\">\n    \n    <p><h4 style=\"color: var(--heading-color, #4db6ac);\">What this table shows:</h4>\n    This table lists test case counts for various <span style=\"color: var(--highlight-color, #81c784); font-weight:bold;\">labels</span> within the application, broken down by execution type (manual or automated) and associated execution status. Each row represents a specific area.</p>\n    \n    <p><h4 style=\"color: var(--heading-color, #4db6ac);\">Why it matters:</h4>\n    We are using for a various reasons and this table provides visibility into how testing efforts are distributed across them. This helps ensure that wehave enough visibility during regression and hardening phases.</p>\n    \n    <p><h4 style=\"color: var(--heading-color, #4db6ac);\">How to interpret:</h4>\n    Since we follow a <span style=\"color: var(--warning-color, #ffb74d); font-weight:bold;\">risk-based testing approach</span>, different labels may have varying levels of risk impact and different meaning so only those who knows what the specific label means can speak on the value of visibility for it</p>\n    \n</div>"
     }
    },
    {
     "type": "table",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "rawSql": "SELECT\n    label,\n    sum(CASE WHEN cycle_short_name LIKE '%Baseline%' THEN 1 ELSE 0 END) AS baseline,\n    sum(CASE WHEN cycle_short_name LIKE '%Automated%' THEN 1 ELSE 0 END) AS automated,\n    sum(CASE WHEN cycle_name NOT LIKE '%Automated%' THEN 1 ELSE 0 END) AS manual,\n    SUM(pass) AS \"Pass\",\n    SUM(fail) AS \"Fail\",\n    SUM(blocked) AS \"Blocked\",\n    SUM(in_progress) AS \"InProgress\",\n    SUM(skipped) AS \"Skipped\",\n    SUM(unexecuted) AS \"Unexecuted\",\n    SUM(in_progress + unexecuted) AS \"Total Unexecuted\",\n    COUNT(*) - SUM(in_progress + unexecuted) AS \"Total Executed\",\n    SUM(total) AS \"Total\"\nFROM athena.mv_test_cycle_statistics\nCROSS JOIN LATERAL jsonb_array_elements_text(label_set) AS label\nWHERE cycle_name LIKE '%Regression%' \n  AND project_code = 'DEMO' \n  AND version = '$version'\n  AND teams_set ? '$team'\n  AND item_execution_rank = 1\nGROUP BY label\nORDER BY label\nLIMIT 10000"
      }
     ]
    }
   ]
  }
 ]
}