{
 "title": "QE :: Teams Overall Regression Statistics",
 "description": "Show the basic regression statistics for all teams",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "athena_datasource", "label": "Athena database", "query": "grafana-postgresql-datasource" },
   {
    "name": "version",
    "label": "version",
    "query": "SELECT distinct version\nFROM athena.mv_test_cycle_statistics\nWHERE item_key ~~* 'demo-t%' and item_type = 'Test' and version like '4%'"
   },
   {
    "name": "team",
    "label": "team",
    "query": "SELECT distinct jsonb_array_elements_text(teams_set)\nFROM athena.mv_test_cycle_statistics\nWHERE item_key ~~* 'demo-t%' and item_type = 'Test' and version = '$version'"
   }
  ]
 },
 "panels": [
  { "title": "$team", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "team" },
  {
   "title": "Regression Inventory",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH categorized_cycles AS (\n    SELECT DISTINCT \n        tcs.item_id,\n        tcs.version,\n        tcs.teams_set,\n        CASE WHEN tcs.cycle_short_name LIKE '%Golden%' THEN 1 ELSE 0 END AS gdb,\n        CASE WHEN tcs.cycle_short_name LIKE '%Automated%' THEN 1 ELSE 0 END AS automated,\n        CASE WHEN tcs.cycle_name NOT LIKE '%Automated%' THEN 1 ELSE 0 END AS manual\n    FROM athena.mv_test_cycle_statistics tcs\n    WHERE \n        tcs.cycle_name LIKE '%Regression%' \n        AND tcs.project_code = 'DEMO' \n        AND tcs.version = '$version'\n        AND tcs.teams_set ? ($team)\n        AND item_execution_rank = 1\n)\nSELECT\n    t.version,\n    SUM(t.automated) AS \"Automated\",\n    SUM(t.manual) AS \"Manual\",\n    SUM(t.gdb) AS \"Dev Automated\"\nFROM categorized_cycles t\nGROUP BY t.version\nORDER BY SUM(t.automated + t.manual + t.gdb)"
    }
   ]
  },
  {
   "title": "Overall Execution Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH categorized_cycles AS (\n    SELECT DISTINCT \n        tcs.item_id,\n        tcs.version,\n        execution_status AS status\n    FROM athena.mv_test_cycle_statistics tcs\n    WHERE \n        tcs.cycle_name LIKE '%Regression%' \n        AND tcs.project_code = 'DEMO' \n        AND tcs.version = '$version'\n        AND item_execution_rank = 1\n        AND EXISTS (\n            SELECT 1\n            FROM jsonb_array_elements_text(tcs.teams_set) AS team\n            WHERE team.value IN ($team)\n        )\n)\nSELECT \n    status,\n    COUNT(*) AS count\nFROM categorized_cycles\nGROUP BY status\nORDER BY count DESC;"
    }
   ]
  },
  {
   "title": "Manual Cycle By Execution Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH categorized_cycles AS (\n    SELECT DISTINCT \n        tcs.item_id,\n        tcs.version,\n        execution_status AS status\n    FROM athena.mv_test_cycle_statistics tcs\n    WHERE \n        tcs.cycle_name LIKE '%Regression%' \n        AND tcs.project_code = 'DEMO' \n        AND tcs.version = '$version'\n        AND item_execution_rank = 1\n        AND tcs.cycle_name NOT LIKE '%Automated%' \n        AND EXISTS (\n            SELECT 1\n            FROM jsonb_array_elements_text(tcs.teams_set) AS team\n            WHERE team.value IN ($team)\n        )\n)\nSELECT \n    status,\n    COUNT(*) AS count\nFROM categorized_cycles\nGROUP BY status\nORDER BY count DESC;"
    }
   ]
  },
  {
   "title": "Automation Cycle By Execution Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH categorized_cycles AS (\n    SELECT DISTINCT \n        tcs.item_id,\n        tcs.version,\n        execution_status AS status\n    FROM athena.mv_test_cycle_statistics tcs\n    WHERE \n        tcs.cycle_name LIKE '%Regression%' \n        AND tcs.project_code = 'DEMO' \n        AND tcs.version = '$version'\n        AND item_execution_rank = 1\n        AND tcs.cycle_short_name LIKE '%Automated%' \n        AND EXISTS (\n            SELECT 1\n            FROM jsonb_array_elements_text(tcs.teams_set) AS team\n            WHERE team.value IN ($team)\n        )\n)\nSELECT \n    status,\n    COUNT(*) AS count\nFROM categorized_cycles\nGROUP BY status\nORDER BY count DESC;"
    }
   ]
  },
  {
   "title": "Manual Test Cycles Execution Status",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    cycle_short_name AS \"Test Cycle\",\n    SUM(pass + \"blocked\" + skipped + fail) / Sum(total)::float * 100 AS \"Total Executed\"\nFROM athena.mv_test_cycle_statistics\nWHERE cycle_name LIKE '%Regression%' \n    AND project_code = 'DEMO' \n    AND cycle_name NOT LIKE '%Automated%' \n    AND version = '$version'\n    AND EXISTS (\n        SELECT 1\n        FROM jsonb_array_elements_text(teams_set) AS team\n        WHERE team.value IN ($team)\n    )\nGROUP BY cycle_short_name\n"
    }
   ]
  },
  {
   "title": "Automation Test Cycles Execution Status",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    cycle_short_name AS \"Test Cycle\",\n    SUM(pass + \"blocked\" + skipped + fail) / Sum(total)::float * 100 AS \"Total Executed\"\nFROM athena.mv_test_cycle_statistics\nWHERE cycle_name LIKE '%Regression%' \n    AND project_code = 'DEMO' \n    AND version = '$version'\n    AND cycle_short_name LIKE '%Automated%' \n    AND version = '$version'\n    AND EXISTS (\n        SELECT 1\n        FROM jsonb_array_elements_text(teams_set) AS team\n        WHERE team.value IN ($team)\n    )\nGROUP BY cycle_short_name\n"
    }
   ]
  }
 ]
}