{{- if and (eq (include "seleniumGrid.useKEDA" $) "true") $.Values.autoscaling.patchObjectFinalizers.enabled (not $.Values.autoscaling.patchObjectFinalizers.serviceAccount) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "seleniumGrid.rbac.role.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  {{- with $.Values.rbacRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    deploymentName: {{ template "seleniumGrid.rbac.role.fullname" $ }}
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
{{- with $.Values.rbacRole.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
