server.port=8084
spring.application.name=metric
athena.schema.name=athena_metric

# Service-specific database user
spring.datasource.username=${ATHENA_METRIC_DB_USERNAME:athena_metric_user}
spring.datasource.password=${ATHENA_METRIC_DB_PASSWORD:athena_metric_user}

spring.config.import=\
  classpath:defaults/spring_fixes.properties,\
  classpath:defaults/datasource.properties,\
  classpath:defaults/demo.properties,\
  classpath:defaults/hikari.properties,\
  classpath:defaults/jpa.properties,\
  classpath:defaults/logging.properties,\
  classpath:defaults/open_feign.properties,\
  classpath:defaults/otel.properties,\
  classpath:defaults/spring_doc.properties

# Cache Configuration
spring.cache.type=caffeine
spring.cache.cache-names=\
  project-by-keyword,\
  project-by-id,\
  environment-by-project-keyword,\
  environment-by-id
spring.cache.caffeine.spec=maximumSize=10000,expireAfterWrite=30m,recordStats
