<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.catools</groupId>
        <artifactId>athena-boot-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../athena-boot-parent/pom.xml</relativePath>
    </parent>

    <artifactId>athena-boot-init</artifactId>

    <name>Athena Database Initializer</name>
    <description>Database initialization service for managing users, roles, and permissions.</description>

    <properties>
        <docker.skip>false</docker.skip>
        <test.skip>true</test.skip>
        <sonar.skip>true</sonar.skip>
    </properties>

    <dependencies>
        <!-- ######################### FLYWAY ########################### -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-flyway</artifactId>
        </dependency>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
            <version>${flyway-database-postgresql.version}</version>
            <scope>runtime</scope>
        </dependency>
        <!-- ######################### /FLYWAY ########################### -->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>org.catools.athena.init.AthenaInitApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
