create table athena_pipeline.execution (before_class_end_time TIMESTAMPTZ, before_class_start_time TIMESTAMPTZ, before_method_end_time TIMESTAMPTZ, before_method_start_time TIMESTAMPTZ, end_time TIMESTAMPTZ not null, executor_id bigint not null, id bigserial not null, pipeline_id bigint not null, start_time TIMESTAMPTZ not null, status_id bigint not null, test_end_time TIMESTAMPTZ, test_start_time TIMESTAMPTZ, class_name varchar(300) not null, method_name varchar(300) not null, package_name varchar(300) not null, parameters varchar(2000), primary key (id));
create table athena_pipeline.execution_metadata (id bigserial not null, name varchar(100) not null, value varchar(2000) not null, primary key (id));
create table athena_pipeline.execution_metadata_mid (execution_id bigint not null, metadata_id bigint not null, primary key (execution_id, metadata_id));
create table athena_pipeline.pipeline (end_date TIMESTAMPTZ, environment_id bigint not null, id bigserial not null, start_date TIMESTAMPTZ not null, version_id bigint not null, name varchar(100) not null, number varchar(100) not null, description varchar(300) not null, primary key (id));
create table athena_pipeline.pipeline_metadata (id bigserial not null, name varchar(100) not null, value varchar(2000) not null, primary key (id));
create table athena_pipeline.pipeline_metadata_mid (metadata_id bigint not null, pipeline_id bigint not null, primary key (metadata_id, pipeline_id));
create table athena_pipeline.scenario_execution (before_scenario_end_time TIMESTAMPTZ, before_scenario_start_time TIMESTAMPTZ, end_time TIMESTAMPTZ not null, executor_id bigint not null, id bigserial not null, pipeline_id bigint not null, start_time TIMESTAMPTZ not null, status_id bigint not null, scenario varchar(500) not null, feature varchar(1000) not null, parameters varchar(2000), primary key (id));
create table athena_pipeline.scenario_metadata_mid (execution_id bigint not null, metadata_id bigint not null, primary key (execution_id, metadata_id));
create table athena_pipeline.status (id bigserial not null, name varchar(100) not null unique, primary key (id));
alter table if exists athena_pipeline.execution add constraint FKsxj934bma70rv4nxhl9jks1tg foreign key (executor_id) references athena_core.user;
alter table if exists athena_pipeline.execution add constraint FK2a1eitje846p27egcbpnpu216 foreign key (pipeline_id) references athena_pipeline.pipeline;
alter table if exists athena_pipeline.execution add constraint FKl5b63e2atpci888j3vrih9fgk foreign key (status_id) references athena_pipeline.status;
alter table if exists athena_pipeline.execution_metadata_mid add constraint FKickcqlum2vg9let6scpuwkr3b foreign key (metadata_id) references athena_pipeline.execution_metadata;
alter table if exists athena_pipeline.execution_metadata_mid add constraint FKm9u1oqvmevg9d5qy25mi8h10x foreign key (execution_id) references athena_pipeline.execution;
alter table if exists athena_pipeline.pipeline add constraint FK50lhemdi8a649a2wukj2ev0g5 foreign key (environment_id) references athena_core.environment;
alter table if exists athena_pipeline.pipeline add constraint FKpqnqm8tes84nhowr2ryitq258 foreign key (version_id) references athena_core.app_version;
alter table if exists athena_pipeline.pipeline_metadata_mid add constraint FKcs5r08ptgvp6eijpulce3dsm0 foreign key (metadata_id) references athena_pipeline.pipeline_metadata;
alter table if exists athena_pipeline.pipeline_metadata_mid add constraint FKg07aj55k425j3nwva53a6a2pd foreign key (pipeline_id) references athena_pipeline.pipeline;
alter table if exists athena_pipeline.scenario_execution add constraint FKgytyony4rytg2x9sac7bppbij foreign key (executor_id) references athena_core.user;
alter table if exists athena_pipeline.scenario_execution add constraint FK5vc883jpgoqbpeqk0pxyvthor foreign key (pipeline_id) references athena_pipeline.pipeline;
alter table if exists athena_pipeline.scenario_execution add constraint FKdwx5wr1r46p3dd78c9pbp8pbx foreign key (status_id) references athena_pipeline.status;
alter table if exists athena_pipeline.scenario_metadata_mid add constraint FKohg9ibf8as6d3gnd3yqg0hu0f foreign key (metadata_id) references athena_pipeline.execution_metadata;
alter table if exists athena_pipeline.scenario_metadata_mid add constraint FKacptnescmpf3du47da8ihq9ps foreign key (execution_id) references athena_pipeline.scenario_execution;
