CREATE SCHEMA athena_tms;
create table athena_tms.cycle (unique_hash integer not null unique, end_date TIMESTAMPTZ, id bigserial not null, start_date TIMESTAMPTZ not null, version_id bigint, code varchar(10) not null unique, name varchar(300) not null, primary key (id));
create table athena_tms.execution (created TIMESTAMPTZ not null, cycle_id bigint not null, executed TIMESTAMPTZ, executor_id bigint, id bigserial not null, item_id bigint not null, status_id bigint not null, primary key (id));
create table athena_tms.item (created_by bigint not null, created_on TIMESTAMPTZ not null, id bigserial not null, priority_id bigint not null, project_id bigint not null, status_id bigint not null, type_id bigint not null, updated_by bigint, updated_on TIMESTAMPTZ, code varchar(15) not null unique, name varchar(300) not null, primary key (id));
create table athena_tms.item_metadata_mid (item_id bigint not null, metadata_id bigint not null, primary key (item_id, metadata_id));
create table athena_tms.item_version_mid (item_id bigint not null, version_id bigint not null, primary key (item_id, version_id));
create table athena_tms.metadata (id bigserial not null, name varchar(100) not null, value varchar(2000) not null, primary key (id));
create table athena_tms.priority (id bigserial not null, code varchar(10) not null unique, name varchar(50) not null, primary key (id));
create table athena_tms.status (id bigserial not null, code varchar(10) not null unique, name varchar(50) not null, primary key (id));
create table athena_tms.status_transition (author bigint not null, from_status bigint not null, id bigserial not null, item_id bigint not null, occurred TIMESTAMPTZ, to_status bigint not null, primary key (id));
create table athena_tms.sync_info (end_time TIMESTAMPTZ not null, id bigserial not null, project_id bigint not null, start_time TIMESTAMPTZ not null, action varchar(50) not null, component varchar(100) not null, primary key (id));
create table athena_tms.type (id bigserial not null, code varchar(10) not null unique, name varchar(50) not null, primary key (id));
create index IDXk43tb8sntc046yxf4suq076os on athena_tms.cycle (code);
create index IDXynam1aocxtr559vsbvmxpaaa on athena_tms.execution (created, cycle_id, item_id);
create index IDX6cgogdarkq48dlg1lbnv4q1oq on athena_tms.item (code);
create index IDX639erqxmw75u6kt3lfksougmb on athena_tms.priority (code);
create index IDX90n0sv25slo1kmu0tcakhjjed on athena_tms.status (code);
create index IDX6phb53alqcmb7j69am501p02w on athena_tms.type (code);
alter table if exists athena_tms.cycle add constraint FKcd7m2868v4ponviyv5olrew1s foreign key (version_id) references athena_core.app_version;
alter table if exists athena_tms.execution add constraint FKpp38bat6onygn2egn4qvy6isw foreign key (cycle_id) references athena_tms.cycle;
alter table if exists athena_tms.execution add constraint FKsxj934bma70rv4nxhl9jks1tg foreign key (executor_id) references athena_core.user;
alter table if exists athena_tms.execution add constraint FKf3j4r2wk0rnpm1yw1tfhgh554 foreign key (item_id) references athena_tms.item;
alter table if exists athena_tms.execution add constraint FKl5b63e2atpci888j3vrih9fgk foreign key (status_id) references athena_tms.status;
alter table if exists athena_tms.item add constraint FKeybj7ikncx4nkfgrb5i1uadq foreign key (created_by) references athena_core.user;
alter table if exists athena_tms.item add constraint FKlgtnomwfllo9wtrosb0qoffh5 foreign key (priority_id) references athena_tms.priority;
alter table if exists athena_tms.item add constraint FKf60hnjyqgladtp0jw5o0n4e9u foreign key (project_id) references athena_core.project;
alter table if exists athena_tms.item add constraint FKa5r9sug9g4f4kif98va9ro3l2 foreign key (status_id) references athena_tms.status;
alter table if exists athena_tms.item add constraint FK95i2undeuwt7lb0uy1md9wkp9 foreign key (type_id) references athena_tms.type;
alter table if exists athena_tms.item add constraint FKpcquid9hq5dwxrsg5lncnl1rt foreign key (updated_by) references athena_core.user;
alter table if exists athena_tms.item_metadata_mid add constraint FKkxa4n4m61qm69fwj6f0udupkn foreign key (metadata_id) references athena_tms.metadata;
alter table if exists athena_tms.item_metadata_mid add constraint FKenckba4dsvmvpdnc26iqrntil foreign key (item_id) references athena_tms.item;
alter table if exists athena_tms.item_version_mid add constraint FKtjjhljwefqu2xoqxaoxiv6jwt foreign key (version_id) references athena_core.app_version;
alter table if exists athena_tms.item_version_mid add constraint FKkqgy2yskehpg6yftnf6t3gssd foreign key (item_id) references athena_tms.item;
alter table if exists athena_tms.status_transition add constraint FKm8e9n1uv6mwl0c72e3bsxu46o foreign key (author) references athena_core.user;
alter table if exists athena_tms.status_transition add constraint FKqx786lpsnejbs8luvrii363xq foreign key (from_status) references athena_tms.status;
alter table if exists athena_tms.status_transition add constraint FK3ffxqq0j5njpl8ulantbb3p9 foreign key (item_id) references athena_tms.item;
alter table if exists athena_tms.status_transition add constraint FK9tb7aqy88ijc3g9rfcxs5nkdf foreign key (to_status) references athena_tms.status;
alter table if exists athena_tms.sync_info add constraint FKnnvsxyu0mqffcgs3lbxhloite foreign key (project_id) references athena_core.project;
