GRANT USAGE ON SCHEMA athena to athena_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA athena to athena_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA athena GRANT SELECT ON TABLES TO athena_ro;

GRANT USAGE ON SCHEMA athena_core to athena_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA athena_core to athena_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA athena_core GRANT SELECT ON TABLES TO athena_ro;
