create table athena.environment (id bigserial not null, project_code bigint not null, code varchar(10) not null unique, name varchar(100), primary key (id));
create table athena.execution (before_class_end_time timestamp(6), before_class_start_time timestamp(6), before_method_end_time timestamp(6), before_method_start_time timestamp(6), end_time timestamp(6) not null, executor_id bigint, id bigserial not null, pipeline_id bigint, start_time timestamp(6) not null, status_id bigint not null, test_end_time timestamp(6), test_start_time timestamp(6), class_name varchar(300) not null, method_name varchar(300) not null, package_name varchar(300) not null, parameters varchar(300) not null, primary key (id));
create table athena.execution_metadata (id bigserial not null, name varchar(100) not null, value varchar(2000) not null, primary key (id));
create table athena.execution_metadata_mid (execution_id bigint not null, metadata_id bigint not null, primary key (execution_id, metadata_id));
create table athena.pipeline (end_date timestamp(6), environment_code bigint not null, id bigserial not null, start_date timestamp(6) not null, name varchar(100) not null, number varchar(100) not null, description varchar(300) not null, primary key (id));
create table athena.pipeline_metadata (id bigserial not null, name varchar(100) not null, value varchar(2000) not null, primary key (id));
create table athena.pipeline_metadata_mid (metadata_id bigint not null, pipeline_id bigint not null, primary key (metadata_id, pipeline_id));
create table athena.project (code varchar(5) not null unique, id bigserial not null, name varchar(50) not null unique, primary key (id));
create table athena.scenario_execution (before_scenario_end_time timestamp(6) not null, before_scenario_start_time timestamp(6) not null, end_time timestamp(6) not null, executor_id bigint, id bigserial not null, pipeline_id bigint, start_time timestamp(6) not null, status_id bigint not null, parameters varchar(300) not null, scenario varchar(300) not null, feature varchar(1000) not null, primary key (id));
create table athena.scenario_metadata_mid (execution_id bigint not null, metadata_id bigint not null, primary key (execution_id, metadata_id));
create table athena.status (id bigserial not null, name varchar(100) not null unique, primary key (id));
create table athena.user (id bigserial not null, name varchar(300) not null unique, primary key (id));
alter table if exists athena.environment add constraint FK_ENVIRONMENT_PROJECT foreign key (project_code) references athena.project;
alter table if exists athena.execution add constraint FK_EXECUTION_USER foreign key (executor_id) references athena.user;
alter table if exists athena.execution add constraint FK_EXECUTION_PIPELINE foreign key (pipeline_id) references athena.pipeline;
alter table if exists athena.execution add constraint FK_EXECUTION_STATUS foreign key (status_id) references athena.status;
alter table if exists athena.execution_metadata_mid add constraint FKickcqlum2vg9let6scpuwkr3b foreign key (metadata_id) references athena.execution_metadata;
alter table if exists athena.execution_metadata_mid add constraint FKm9u1oqvmevg9d5qy25mi8h10x foreign key (execution_id) references athena.execution;
alter table if exists athena.pipeline add constraint FK_PIPELINE_ENVIRONMENT foreign key (environment_code) references athena.environment;
alter table if exists athena.pipeline_metadata_mid add constraint FKcs5r08ptgvp6eijpulce3dsm0 foreign key (metadata_id) references athena.pipeline_metadata;
alter table if exists athena.pipeline_metadata_mid add constraint FKg07aj55k425j3nwva53a6a2pd foreign key (pipeline_id) references athena.pipeline;
alter table if exists athena.scenario_execution add constraint FK_EXECUTION_USER foreign key (executor_id) references athena.user;
alter table if exists athena.scenario_execution add constraint FK_EXECUTION_PIPELINE foreign key (pipeline_id) references athena.pipeline;
alter table if exists athena.scenario_execution add constraint FK_EXECUTION_STATUS foreign key (status_id) references athena.status;
alter table if exists athena.scenario_metadata_mid add constraint FKohg9ibf8as6d3gnd3yqg0hu0f foreign key (metadata_id) references athena.execution_metadata;
alter table if exists athena.scenario_metadata_mid add constraint FKacptnescmpf3du47da8ihq9ps foreign key (execution_id) references athena.scenario_execution;
