<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <artifactId>athena-bom</artifactId>
    <packaging>pom</packaging>

    <name>Athena - BOM</name>

    <parent>
        <groupId>org.catools</groupId>
        <artifactId>athena-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../athena-parent/pom.xml</relativePath>
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-parent</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-parent</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-model</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-common-test</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-core-feign</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-spec</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-spec-feign</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-git</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-git-feign</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-kube</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-kube-feign</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-metric</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-metric-feign</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-pipeline</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-pipeline-feign</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-tms</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-boot-tms-feign</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-gateway</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-cli-parent</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-cli-atlassian-jira</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-cli-atlassian-scale</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-cli-git</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-cli-kube</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-cli-openapi</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-client-parent</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-client-atlassian-jira</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-client-atlassian-scale</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-client-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-client-git</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-client-kube</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-client-metric</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-client-openapi</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-client-pipeline</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-client-pipeline-testng</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.catools</groupId>
                <artifactId>athena-client-tms</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
