create table athena_kube.container (ready boolean, restart_count integer, started boolean, id bigserial not null, last_sync TIMESTAMPTZ not null, pod_id bigint not null, started_at TIMESTAMPTZ, type varchar(100) not null, image_id varchar(300) not null, name varchar(300) not null, image varchar(1000) not null, primary key (id));
create table athena_kube.container_metadata (id bigserial not null, name varchar(300) not null, value varchar(1000) not null, primary key (id), constraint UniquePodContainerMetadataNameValue unique (name, value));
create table athena_kube.container_metadata_mid (container_id bigint not null, metadata_id bigint not null, primary key (container_id, metadata_id));
create table athena_kube.pod (created_at TIMESTAMPTZ, deleted_at TIMESTAMPTZ, id bigserial not null, last_sync TIMESTAMPTZ not null, project_id bigint not null, status_id bigint not null, uid varchar(36) unique, namespace varchar(100), hostname varchar(200), node_name varchar(200), name varchar(500) unique, primary key (id));
create table athena_kube.pod_annotation (id bigserial not null, name varchar(300) not null, value varchar(1000) not null, primary key (id), constraint UniquePodAnnotationNameValue unique (name, value));
create table athena_kube.pod_annotation_mid (annotation_id bigint not null, pod_id bigint not null, primary key (annotation_id, pod_id));
create table athena_kube.pod_label (id bigserial not null, name varchar(300) not null, value varchar(1000) not null, primary key (id), constraint UniquePodLabelNameValue unique (name, value));
create table athena_kube.pod_label_mid (label_id bigint not null, pod_id bigint not null, primary key (label_id, pod_id));
create table athena_kube.pod_metadata (id bigserial not null, name varchar(300) not null, value varchar(1000) not null, primary key (id), constraint UniquePodMetadataNameValue unique (name, value));
create table athena_kube.pod_metadata_mid (metadata_id bigint not null, pod_id bigint not null, primary key (metadata_id, pod_id));
create table athena_kube.pod_selector (id bigserial not null, name varchar(300) not null, value varchar(1000) not null, primary key (id), constraint UniquePodSelectorNameValue unique (name, value));
create table athena_kube.pod_selector_mid (pod_id bigint not null, selector_id bigint not null, primary key (pod_id, selector_id));
create table athena_kube.pod_status (id bigserial not null, name varchar(200), phase varchar(200), message varchar(1000), reason varchar(1000), primary key (id), constraint UniquePodStatus unique (name, phase, message, reason));
alter table if exists athena_kube.container add constraint FKidh5jk8n2x46l91nky124f39s foreign key (pod_id) references athena_kube.pod;
alter table if exists athena_kube.container_metadata_mid add constraint FK10djf8c16osesuevhauhvdgim foreign key (metadata_id) references athena_kube.container_metadata;
alter table if exists athena_kube.container_metadata_mid add constraint FKhv0j50ewf7u0uryjryeauc4cn foreign key (container_id) references athena_kube.container;
alter table if exists athena_kube.pod add constraint FKpqmjd8srmogc90vxm50sdsed9 foreign key (project_id) references athena_core.project;
alter table if exists athena_kube.pod add constraint FKr3p5honftoe7g7fpgabvthmke foreign key (status_id) references athena_kube.pod_status;
alter table if exists athena_kube.pod_annotation_mid add constraint FK13s5ctig92ec26h8n6ba1ixxe foreign key (annotation_id) references athena_kube.pod_annotation;
alter table if exists athena_kube.pod_annotation_mid add constraint FKbsdp5kgjsgktynla364170iok foreign key (pod_id) references athena_kube.pod;
alter table if exists athena_kube.pod_label_mid add constraint FKpwbwcs37hrmr2a7n6its4ber0 foreign key (label_id) references athena_kube.pod_label;
alter table if exists athena_kube.pod_label_mid add constraint FKq3cf8vm17h8stqg7j6chwfw25 foreign key (pod_id) references athena_kube.pod;
alter table if exists athena_kube.pod_metadata_mid add constraint FK8cy7fosd0on1gbkv0pabjabn1 foreign key (metadata_id) references athena_kube.pod_metadata;
alter table if exists athena_kube.pod_metadata_mid add constraint FKbli9a215pefyl6ggyjsvpitid foreign key (pod_id) references athena_kube.pod;
alter table if exists athena_kube.pod_selector_mid add constraint FKo5hm5rb7fmfxo7qfvw5kaqqbf foreign key (selector_id) references athena_kube.pod_selector;
alter table if exists athena_kube.pod_selector_mid add constraint FKjdcsuuueuitqspc96yi3ms00p foreign key (pod_id) references athena_kube.pod;
